version: '3.8'
services:
  spring-app:
    image: fe3049a6c73e9eb1af8ac23dfc86f31addcd1f6ff8a5af0d3437cc25d429e1be
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: dockerUzduotis
    ports:
      - "3307:3306"